### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by lautis** [mavenlink/alaska#1]
Gemspec mentions GPL license, but there is no LICENSE.txt or any other copyright declaration. GPL would make this a bit hard to use in proprietary products. While you're not technically distributing an application when hosting a web app, legal departments usually treat this as a red herring.

Would you consider switching to MIT license, or perhaps LGPL if you you're concerned about sharing modifications? In any case, there probably should be a LICENSE.txt file to clearly state the project's license.

**Comment by diclophis** [comment]
Please see the referenced PR, we use a MIT for most of our open-source stuff at mavenlink.
