### ISSUE TITLE
Initializer error - Cannot load such file .../config/initializers/alaska.rb

### ISSUE THREAD

**Issue by giovannibonetti** [mavenlink/alaska#13]
When trying to use Alaska in my app I get the following error:

```
.../config/initializers/alaska.rb:5:in `<top (required)>': cannot load such file -- runtime (LoadError)
```

It is related to this line:

```ruby
# config/initializers/alaska.rb
require 'alaska'

if Rails.env == "development" || Rails.env == "test" || ENV["RAILS_GROUPS"] == "assets"
  # use alaska.js pipelining only when precompiling assets
  ExecJS.runtime = Alaska::Runtime.new(:debug => true) # <= ******* Error here ***********
end
```

I guess it is related to the directory structure of the lib:

`alaska/lib/alaska.rb`
`alaska/lib/context.rb`
`alaska/lib/runtime.rb`

I though Rails works best with a structure like this:

`alaska/lib/alaska.rb`
`alaska/lib/alaska/context.rb`
`alaska/lib/alaska/runtime.rb`

But maybe I'm wrong

**Comment by diclophis** [comment]
Hello, sorry for the delay in response... I have replicated the problem on my workstation and I am starting to investigate the problem now.

It does appear to be directly related to using the `rubygems` version of the gem instead of the `git` form in the `Gemfile` ... I will have to dig in and see whats wrong, but in the mean time please use this form

`gem 'alaska', :git => 'git@github.com:mavenlink/alaska.git'`

to include alaska into your project

**Comment by cantino** [comment]
@diclophis, I believe that @giovannibonetti is correct: we should make the following gem layout:

```
lib/
  alaska.rb
  alaska/
      runtime.rb
      context.rb
      version.rb
```

where alaska.rb is:

```ruby
require 'alaska/runtime.rb'
require 'alaska/context.rb'
```

and runtime.rb is:

```ruby
module Alaska
  module Runtime
    ...
  end
end
```

etc.  Often the gemspec will require the alaska/version.rb file, although this is optional.

Ruby adds all gems to the load path, so putting anything in lib/ makes it global.  This means that `context.rb` and `runtime.rb` would be required in any project as `require 'runtime'`, when we'd prefer them to be `require 'alaska/runtime'`.

**Comment by diclophis** [comment]
ok yea, that makes sense

**Comment by diclophis** [comment]
@giovannibonetti I have `v1.0.4` building now for our application as a test, I will close this and merge https://github.com/mavenlink/alaska/pull/14 when its good to go

**Comment by diclophis** [comment]
ok, looks like its working in our main app, built as a pure gem dep. instead of a `git:` dep. in the gemfile.

Again, thank you for your interest in this project... I hope to hear some good news regarding any performance gains achieved by using `alaska`

**Comment by diclophis** [comment]
also note, the instructions have changed to read `require "alaska/runtime"` now

**Comment by giovannibonetti** [comment]
@diclophis Thanks, it seems to work fine at my machine! I will bundle it in my app soon and hope my coworkers like it!
