### ISSUE TITLE
Similar project Fastnode

### ISSUE THREAD

**Issue by sfcgeorge** [mavenlink/alaska#20]
Just making both projects aware of each other so that the maintainers might borrow ideas, join forces, or just so people googling can see alternatives. https://github.com/jhawthorn/execjs-fastnode

**Comment by diclophis** [comment]
@sfcgeorge thanks for the heads up... def. looks like there could be some synergy here

**Comment by diclophis** [comment]
https://github.com/mavenlink/alaska/pull/22
