### ISSUE TITLE
Unexpected error while processing request: TypeError: Object #<Object> has no method 'attachEvent'

### ISSUE THREAD

**Issue by austinfromboston** [mavenlink/alaska#9]
Hey folks,

Thanks for making this gem.  I'm seeing some instability while testing it out and wondering if you've got any insight.  Seems like every few times I boot the execjs server I'll get a whole slew of the following errors.  If I'm running specs, all specs in the suite will fail with the same error.

Listening on port /var/folders/1g/9s__749n6zs2kb3nfqxs8sx00000gp/T/alaska20150317-13603-11cdrss alaska.js started 
Unexpected error while processing request: TypeError: Object #<Object> has no method 'attachEvent'

Is there any kind of log for tracking down what is causing this error?

**Comment by diclophis** [comment]
Interesting, to start with, lets get a list of the following together:

1. Generic make/model of your application (e.g. railsX w/ foo.js)
2. Other additional gems that depend on execjs (this is likely the biggest source of problems)
3. Ideally some repro scenario / code snippet I could use to develop a regression test

In general, the biggest source of problems is likely some library using execjs in a manner that breaks its assumptions, namely that the `context#eval` calls are wrapped in an anon-self-executing JS function, and that it is safe to only execute `ExecJS.compile` once per "session"

**Comment by austinfromboston** [comment]
Cool -- we're in a Rails 4 app using backbone, jquery and a few other regular libs
    #= require jquery
    #= require jquery_ujs
    #= require jquery.validate
    #= require underscore
    #= require underscore.string
    #= require js-routes
    #= require shared/ie_polyfill
    #= require backbone
    #= require hamlcoffee
    #= require fancybox
    #= require moment_ago
    #= require highcharts
    #= require highcharts/highcharts-more
    #= require bootstrap
    #= require easypiechart
    #= require modernizr
    #= require jquery-ui/datepicker
    #= require jquery-ui/spinner
    #= require jquery-ui/slider
    #= require jquery.expandable
    #= require jquery.expander
    #= require jquery.validate.additional-methods

Gems that depend on execjs are:
    backbone-on-rails (1.1.0.0)

**Comment by diclophis** [comment]
Ok, if you still want to give a couple things a try I would see if you could get your Gemfile.lock setup so that you are using `coffee-script (2.2.0)`

Here are the versions we use at mavenlink that work OK:

    alaska (0.0.7) git-sha: 8779e8c198f4f6d0042825d1a8e9d1fe70232c57
    autoprefixer-rails (5.1.7)
    coffee-script (2.2.0)
    uglifier (2.7.0)

**Comment by austinfromboston** [comment]
Pegged to those versions, but still seeing 'has no method attachEvent' -- i think these errors are from modernizr.  When I drop modernizr, I see 'SyntaxError: Illegal return statement' -- even if I remove all includes from the referenced file.
